# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'example' do
  react_native_path = '../node_modules/react-native'
  third_party_path = react_native_path+'/third-party-podspecs'

  pod 'Yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path, :subspecs => [
    'CxxBridge',
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'RNGLModelView', :path => '../..'

  pod 'Folly', :podspec => "#{third_party_path}/Folly.podspec"
  pod 'GLog', :podspec => "#{third_party_path}/GLog.podspec"
  pod 'DoubleConversion', :podspec => "#{third_party_path}/DoubleConversion.podspec"
end
